name: PDF-FromHTML
version: 0.00_01
abstract: Convert HTML documents to PDF
author: Autrijus Tang <autrijus@autrijus.org>
license: perl
distribution_type: module
requires:
  XML::Twig: 0
  XML::Clean: 0
  PDF::Writer: 0.01
  PDF::API2: 0.40_52
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
