name: PDF-FromHTML
version: 0.12
abstract: Convert HTML documents to PDF
license: perl
distribution_type: module
requires:
  perl: 5.6.0
  List::Util: 0
  XML::Twig: 0
  Graphics::ColorNames: 0
  LWP::Simple: 0
  Image::Size: 0
  PDF::Writer: 0.05
  PDF::Template: 0.30
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.40
