--- 
abstract: Convert HTML documents to PDF
author: 
  - Audrey Tang <cpan@audreyt.org>
distribution_type: module
generated_by: Module::Install version 0.68
license: MIT
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: PDF-FromHTML
no_index: 
  directory: 
    - inc
    - t
requires: 
  Graphics::ColorNames: 0
  Image::Size: 0
  LWP::Simple: 0
  List::Util: 0
  PDF::Writer: 0.05
  XML::Twig: 0
  perl: 5.6.0
version: 0.26
